# Generated by Django 2.2.3 on 2020-02-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20191127_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='readmore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_pics')),
                ('heading', models.CharField(max_length=400)),
                ('discription', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
